language: ruby
gemfile:
   - test/support/Gemfile
rvm:
  - 1.9.3
  - 2.0.0
script:
  - bundle exec foodcritic --epic-fail any ./
  - bundle exec kitchen test --parallel --log-level=info --destroy=always
